gel-rb/gel

- lib/gel/package/installer.rb
Fix this error if you run the test with just `rake`:
```
1) Error:
ActivateTest#test_activate_gem_with_extensions:
NameError: uninitialized constant Gel::Package::Installer::GemInstaller::Shellwords
```
> Need to require shellwords

- lib/gel/error.rb
- lib/gel/package/installer.rb
- test/install_test.rb
Hey 👋 
Since this project has a `.rubocop.yml` file, I guessed that doing some rubocop refactoring wouldn't be bad. Thats what I did here. Also extracted the `mkrf_conf` errors to the `lib/errors.rb`
Together with #29 all rubocop warnings / errors should be fixed now 🙂
> REF: Moved mkrf_conf error to errors lib

- lib/gel/command/shell_setup.rb
I'm running on [Fish shell](https://fishshell.com) and the current shell setup doesn't work for me, without having to manually modify it. This introduces support for fish shell extension and possibly a small abstraction that can be reused if other shells that don't use the standard bash/zsh-like syntax need to be supported.
> Introduce Fish shell support

- lib/gel/command/help.rb
- test/cli_test.rb
- test/command/help_test.rb
- test/test_helper.rb
This Pull Request implements part of #36.
I will add support for `-h` and `--help` in coming Pull Request if we want to.
```
$ gel help
Gel is a modern gem manager.
Usage:
gel help       Print this help message.
gel install    Install the gems from Gemfile.
gel lock       Update lockfile without installing.
gel exec       Run command in context of the gel.
Further information:
https://gel.dev/
```
Currently prints a very basic help message.
```
bin/setup && bin/rake
```
> Add basic gel help command

- lib/gel/lock_parser.rb
- test/lock_parser_test.rb
- test/resolved_gem_set_test.rb
This PR adds support of parsing `RUBY VERSION` of lockfile to `LockParser` and a test for `Gel::ResolvedGemSet`.
```
bin/setup && bin/rake
```
> Add support to parse RUBY VERSION in Lock parser and a test for resolved gem set

- lib/gel/gemfile_parser.rb
- test/gemfile_parser_test.rb
This Pull Request is for #56.
- Extract into `RunningRuby` in order to stub the constant in tests
```
bin/setup && bin/rake
```
```
/Users/juanitofatas/src/github.com/matthewd/gel/exe/gel install
```
Not related to the changes from this Pull Request, but I am having a weird issue that throws an error at local (See https://github.com/gel-rb/gel/issues/61)
> Add support for specify multiple Ruby versions

- lib/gel/gemspec_parser.rb
I was doing some puts debugging, and that caused an error here because my puts was messing up the Marshal output.
I could have used `$stderr.puts` for my debugging, but I think we might as well use a non-standard (non-default?) fd to pass this data.
> Don't pass Marshal data over STDOUT in GemspecParser

- lib/gel/resolved_gem_set.rb
- test/resolve_test.rb
- test/test_helper.rb
This Pull Request fixes #65.
- Added a test helper method `assert_nothing_raised` 5a9fec7
- Fix the bug in `dump` 5a9fec7...f99c1e1
- The test is the minimum to reproduce the failure, not being able to resolve the whole lockfile.
```
bin/setup && bin/rake
```
> Fix resolving gem when there is no lockfile

- lib/gel/environment.rb
- lib/gel/gemfile_parser.rb
- test/gemfile_parser_test.rb
- test/lock_activate_test.rb
`install_if` is [a poorly documented](https://bundler.io/man/gemfile.5.html#INSTALL_IF) Gemfile method, but it actually has the following behaviours:
1. It accepts multiple conditions that all have to evaluate to true for the gem to be installed
2. It has both a block form and an inline form that operate in the same fashion.
3. Any gem that is ultimately marked as `install_if: false` is considered during resolution but is filtered as an install candidate (similar to how `platforms` works)
This PR aims to add support for all those behaviours inline with the Gel workflow:
1. `install_if` methods are converted to options on the current stack for block-form usages and merged with inline usages. 
2. When adding a gem to the list of resolved gems, the `install_if` conditions collected in the …
> Implement `install_if` processing

- lib/gel.rb
Ran the command `bin/console` in my Sinatra based app whilst having gel setup in my path, and ran into a missing require error;
```
Traceback (most recent call last):
8: from bin/console:3:in `<main>'
7: from /Users/haroon/projects/gel/lib/gel/compatibility/rubygems.rb:197:in `require'
6: from /Users/haroon/projects/gel/lib/gel/compatibility/rubygems.rb:197:in `require'
5: from /Users/haroon/projects/gel/lib/gel/compatibility/bundler/setup.rb:4:in `<top (required)>'
4: from /Users/haroon/projects/gel/lib/gel/compatibility/bundler.rb:5:in `setup'
3: from /Users/haroon/projects/gel/lib/gel/environment.rb:355:in `activate'
2: from /Users/haroon/projects/gel/lib/gel/environment.rb:97:in `load_gemfile'
1: from /Users/haroon/projects/gel/lib/gel/gemfile_parser.rb:4:in `parse' …
```
> Add gel/errors to gel.rb

- lib/gel/gemspec_parser.rb
- test/gemspec_parser_test.rb
This option was seen in the wild here:
https://github.com/codahale/bcrypt-ruby/blob/master/bcrypt.gemspec
After this patch, it works:
```
[aaron@TC ~/g/bcrypt-ruby (update-deps)]$ ruby --disable-gems -I ~/git/gel/lib ~/git/gel/bin/gel install
Installing rspec-support (3.8.0)
Installing diff-lcs (1.3)
Installing rake-compiler (0.9.9)
Installing rspec-mocks (3.8.0)
Installing rspec-expectations (3.8.3)
Installing rspec (3.8.0)
Installing rspec-core (3.8.0)
Installed 7 gems
```
> Add `extra_rdoc_files` to the gemspec parser

- lib/gel/pinboard.rb
```
% gel install
Fetching sources....Unhandled exception in work pool "gel-catalog-prep" for job "catalog":
.../gel/lib/gel/pinboard.rb:122:in `block in updated'
/usr/local/rbenv/versions/2.6.2/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
.../gel/lib/gel/pinboard.rb:121:in `updated'
.../gel/lib/gel/tail_file.rb:98:in `block (2 levels) in update'
.../gel/lib/gel/tail_file.rb:45:in `times'
.../gel/lib/gel/tail_file.rb:45:in `block in update'
.../gel/lib/gel/tail_file.rb:42:in `open'
.../gel/lib/gel/tail_file.rb:42:in `update'
.../gel/lib/gel/pinboard.rb:58:in `block (2 levels) in async_file'
.../gel/lib/gel/work_pool.rb:62:in `block (4 levels) in start'
.../gel/lib/gel/work_pool.rb:47:in `loop'
.../gel/lib/gel/work_pool.rb:47:in `block (3 levels) in start' …
```
> Fix: Gel::Pinboard#read may return nil

- lib/gel/db.rb
- test/db_test.rb
SDBM's limits are on the key/value pair, not on the value alone. This adjusts the split algorithm to factor in key size as well for a dynamic split size.
> SDBM split size

- lib/gel/catalog/marshal_hacks.rb
The Gem namespace may not have been defined yet as this file gets loaded just before the rubygems compatibility layer. This could be moved into the compatibility layer, but it seems to have been separated so that it is independently loadable. So maybe this is better? Fixes #79.
> Fix missing Gem namespace

- lib/gel/installer.rb
- lib/gel/store_catalog.rb
This Pull Request fixes warnings spotted from [Build #244](https://buildkite.com/matthewd/gel/builds/224#0f59c415-b035-4bfd-97b7-d7d75b9a57de):
```
|  
| ............../app/lib/gel/store_catalog.rb:20: warning: shadowing outer local variable - name
| /root/.local/gel/ruby/gems/pub_grub-0.5.0/lib/pub_grub/partial_solution.rb:38: warning: shadowing outer local variable - assignment
| ...........S........................................./app/lib/gel/installer.rb:146: warning: shadowing outer local variable - g
| ./app/lib/gel/installer.rb:146: warning: shadowing outer local variable - g
| ...
|  
| Finished in 21.411552s, 3.3160 runs/s, 13.0303 assertions/s.
|  
| 71 runs, 279 assertions, 0 failures, 0 errors, 1 skips
```
> Fix shadowing outer local variable warnings

- lib/gel/compatibility/rubygems.rb
- lib/gel/compatibility/rubygems/package_task.rb
- lib/gel/direct_gem.rb
We're currently still not aiming to be able to produce a packaged gem -- but we can fake out the parts rake-compiler needs while it's just trying to set up its rake tasks.
The goal is to allow a rake-compiler-using gem (such as Puma) to work in local use, and support `rake compile`, under Gel. Actual packaging for distribution is best left to Bundler & Rubygems.
Fixes #77
> Provide enough empty shells that rake-compiler can (partly) work

- lib/gel/catalog/compact_index.rb
- lib/gel/catalog/dependency_index.rb
- lib/gel/catalog/legacy_index.rb
- lib/gel/resolved_gem_set.rb
This fixes a number of:
"Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call"
warnings.
> Fix ruby 2.7 deprecations

- lib/gel/command.rb
- lib/gel/command/version.rb
- test/cli_test.rb
- test/command/help_test.rb
- test/command/version_test.rb
I noticed that the man page includes a `--version` flag, but doesn't implement it. This adds that and the `--help` flag with their abbreviations.
> Add flags for version and help

- lib/gel/environment.rb
By removing the existance-of-lock-file check and the search-upwards check the lockfile
can be requested via `gel lock` and end up in the project root dir.
fix: #104
> Proposal to stop gel looking for / putting lockfile in strange places.

- .buildkite/pipeline.yml
- lib/gel/gemspec_parser.rb
- lib/gel/runtime.rb
The conditionvariable bug we were avoiding in CI is fixed, as is the problem with overriding existing environment variables in `spawn`.
So we can return CI to running the latest, and we can drop the ugly `GEL_DISABLED` workaround.
In the long term we should support a wider range of JRuby versions, but for now, I think it's fine to [silently] require a quite recent release.
> Get in sync with latest JRuby

- lib/gel/environment.rb
- lib/gel/lock_loader.rb
- lib/gel/resolved_gem_set.rb
- test/resolve_test.rb
- test/write_lockfile_test.rb
When a gem is added or removed from the Gemfile, the Gemfile.lock now updates automatically.
This does mean that gel will now write the Gemfile.lock more often which means more dependency solving.
This behavior more closely matches bundler and prevents confusion around when your Gemfile and Gemfile.lock might not be in sync.
<details><summary>Current Behavior</summary>
```shell
$ ls
Gemfile
$ cat Gemfile
source 'https://rubygems.org'
gem 'httparty'
$ gel install
Fetching sources...
.
Resolving dependencies...
Writing lockfile to /Users/hparker/code/ruby_home/Gemfile.lock
$ cat Gemfile.lock
GEM
remote: https://rubygems.org/
specs:
httparty (0.18.0)
mime-types (~> 3.0)
multi_xml (>= 0.5.2)
mime-types (3.3.1)
mime-types-data (~> 3.2015)
mime-types-data (3.2019.1009)
multi_xml (0.6.0) …
```
> Automatically update Gemfile.lock when out of date

- lib/gel/compatibility/rubygems.rb
Here, we're rearranging how we override the global `require`, so that bootsnap will find and use ours, instead of directly hitting the C method.
In passing, also add `Gem.dir` for Logster -- which will allow it to boot, though honestly seems unlikely to be helpful, given our differing directory structure.
> Improve compatibility with bootsnap

- lib/gel/environment.rb
- lib/gel/git_catalog.rb
- lib/gel/lock_loader.rb
- lib/gel/resolved_gem_set.rb
- test/write_lockfile_test.rb
body isn't there for a freshly-resolved entry; instead of back-filling it, let's just use real objects more often. Storing the raw body was always a cop-out anyway.
This fixes #112, a bug I introduced in 70e57c3badc7f8837a979cf952687fa401bcc608 -- though it was actually a latent issue / oversight in #57.
> Use the resolved gem's #catalog, not #body

- Rakefile
- lib/gel/package/installer.rb
- test/install_test.rb
- test/write_lockfile_test.rb
Hi, thanks for your fantastic gem!
We would like to fix behavior for a non-matching filter which currently blocks us from using your gem:
* if the package contains a file with an ending not in %w[.rb #{DLEXT} #{DLEXT2}], i.e. somefile.kex - we don't want to track it 
What we changed:
* Deleted unused variable
* Added problematic package for testing purposes
* Added test for this case
* Removed unused variable
> Fix non-matching filter
